baseURL = 'https://huanglifang11.github.io/newsite//'
languageCode = 'en-us'
publishDir= "docs"
hasCJKLanguage = true
summaryLength = 30
theme = 'ananke'
title = '宠物友好型城市'
canonifyurls = true
[markup]
defaultMarkdownHandler="goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe=true
